name: Secret Check

on: push

jobs:
  check-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Check APP_TOKEN
        env:
          APP_TOKEN: ${{ secrets.APP_TOKEN }}
        run: |
          if [ -n "$APP_TOKEN" ]; then
            echo "APP_TOKEN is set"
          else
            echo "APP_TOKEN is not set"
            exit 1
          fi
